repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.4.0
  hooks:
  - id: check-merge-conflict
  - id: check-ast
  - id: check-yaml
  - id: check-toml
  - id: check-json
  - id: pretty-format-json
    args: [--autofix, --no-sort-keys, --no-ensure-ascii]
  - id: check-case-conflict
  - id: check-added-large-files
  - id: mixed-line-ending
  - id: end-of-file-fixer
    exclude: static
  - id: trailing-whitespace
    exclude: static
  - id: forbid-new-submodules
  - id: check-merge-conflict
  # - id: no-commit-to-branch
  #   args: [--branch, master]

- repo: https://github.com/psf/black
  rev: 23.9.1
  hooks:
  - id: black
    args: [--line-length=120]
    exclude: migrations

- repo: https://github.com/pycqa/isort
  rev: 5.12.0
  hooks:
  - id: isort
    name: isort (python)
    args: [--profile=black]
    exclude: |
        (?x)(
            migrations |
            __init__.py
        )

- repo: https://github.com/pycqa/flake8
  rev: 6.1.0
  hooks:
  - id: flake8
    args: [--max-line-length=120]
    exclude: migrations

- repo: https://github.com/RobertCraigie/pyright-python
  rev: v1.1.332
  hooks:
  - id: pyright
